# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disambigauation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset', models.CharField(max_length=40)),
                ('definition', models.TextField()),
            ],
            options={
                'verbose_name': 'Disambigauation',
                'verbose_name_plural': 'Disambigauations',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=80)),
                ('paragraph', models.TextField()),
                ('disambigauation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disambigauation')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
