# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-26 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disambigauation',
            new_name='Disambiguation',
        ),
        migrations.AlterModelOptions(
            name='disambiguation',
            options={'verbose_name': 'Disambiguation', 'verbose_name_plural': 'Disambiguations'},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='disambigauation',
            new_name='Disambiguation',
        ),
    ]
