# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-26 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170226_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='Disambiguation',
            new_name='disambiguation',
        ),
    ]
