# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170226_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('pageid', models.IntegerField()),
                ('extract', models.TextField()),
            ],
            options={
                'verbose_name': 'WikiPage',
                'verbose_name_plural': 'WikiPages',
            },
        ),
        migrations.AddField(
            model_name='search',
            name='term_lemma',
            field=models.CharField(default='hello', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='disambiguation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Disambiguation'),
        ),
        migrations.AddField(
            model_name='search',
            name='wikipage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.WikiPage'),
            preserve_default=False,
        ),
    ]
