# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170303_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=80)),
                ('training_data', models.TextField()),
            ],
            options={
                'verbose_name': 'Classifier',
                'verbose_name_plural': 'Classifiers',
            },
        ),
        migrations.RemoveField(
            model_name='search',
            name='disambiguation',
        ),
        migrations.AddField(
            model_name='search',
            name='correct_wiki_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Disambiguation',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='classifier',
            field=models.ManyToManyField(to='core.Classifier'),
        ),
    ]
