# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-19 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170313_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='classifier',
        ),
        migrations.DeleteModel(
            name='Classifier',
        ),
    ]
