# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-19 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170319_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikipage',
            old_name='pageid',
            new_name='page_id',
        ),
    ]
