# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170319_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='correct_wiki_returned',
            field=models.BooleanField(),
        ),
    ]
